theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
end-of-line-diagnostics = "hint"
rulers = [120]
true-color = true
mouse = false
auto-format = true
# bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
other-lines = "disable"  # Don't expand diagnostics unless the cursor is on the line

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

# Some characters that work well: "▏", "┆", "┊", "⸽"
character = "▏"
# skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-x = "extend_to_line_bounds"
X = "select_line_above"
C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

C-y = [
      ':sh rm -f /tmp/unique-file',
      ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
      ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
      ':open %sh{cat /tmp/unique-file}',
      ':redraw',
]

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.insert]
"C-[" = "normal_mode"
'j'	= {f='normal_mode','j'={'f'=[':insert-output /bin/echo -n j','move_char_right','normal_mode']}}

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "diagnostics"]
right= ["register", "total-line-numbers", "position", "selections", "primary-selection-length"]





